// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9CAXRY4Bual1BMlsy5CyBweg6mW_MN2M',
    appId: '1:859078273796:web:407ccca5d18fc2d6a17e51',
    messagingSenderId: '859078273796',
    projectId: 'biochem-b5d74',
    authDomain: 'biochem-b5d74.firebaseapp.com',
    storageBucket: 'biochem-b5d74.firebasestorage.app',
    measurementId: 'G-670V6PJ1DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOajxqGhYcIuE-xvomozSMOEg6y_cUbg4',
    appId: '1:859078273796:android:e215e9ea2e0ec1c0a17e51',
    messagingSenderId: '859078273796',
    projectId: 'biochem-b5d74',
    storageBucket: 'biochem-b5d74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEI_9-EcjChmmlyug6zxNVrkn6Zf2ADK0',
    appId: '1:859078273796:ios:d1ba55160873c8caa17e51',
    messagingSenderId: '859078273796',
    projectId: 'biochem-b5d74',
    storageBucket: 'biochem-b5d74.firebasestorage.app',
    iosBundleId: 'com.example.biochem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEI_9-EcjChmmlyug6zxNVrkn6Zf2ADK0',
    appId: '1:859078273796:ios:d1ba55160873c8caa17e51',
    messagingSenderId: '859078273796',
    projectId: 'biochem-b5d74',
    storageBucket: 'biochem-b5d74.firebasestorage.app',
    iosBundleId: 'com.example.biochem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9CAXRY4Bual1BMlsy5CyBweg6mW_MN2M',
    appId: '1:859078273796:web:527c7e131a5a9190a17e51',
    messagingSenderId: '859078273796',
    projectId: 'biochem-b5d74',
    authDomain: 'biochem-b5d74.firebaseapp.com',
    storageBucket: 'biochem-b5d74.firebasestorage.app',
    measurementId: 'G-TW2YZYB4NH',
  );
}
